# Generated by Django 4.2.1 on 2023-05-27 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('site', models.URLField()),
                ('token', models.CharField(max_length=32)),
                ('login', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Waiting for acceptation'), ('accepted', 'Application accepted'), ('rejected', 'Application rejected'), ('banned', 'Company banned')], default='pending', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField()),
                ('side_of_comment', models.CharField(choices=[('user', 'User comment'), ('company', 'Company reply')], max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companies')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
