# Generated by Django 4.2.1 on 2023-05-29 01:06

import api.models.opinions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companies_alter_user_id_opinions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinions',
            name='side_of_comment',
        ),
        migrations.AddField(
            model_name='companies',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinions',
            name='company_response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='rating',
            field=models.FloatField(validators=[api.models.opinions.validate_interval]),
        ),
    ]
