# Generated by Django 4.2.1 on 2023-05-29 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_opinions_comment_date_opinions_rating_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safety_Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=7)),
                ('word2', models.CharField(max_length=7)),
                ('word3', models.CharField(max_length=7)),
                ('word4', models.CharField(max_length=7)),
                ('word5', models.CharField(max_length=7)),
                ('word6', models.CharField(max_length=7)),
                ('word7', models.CharField(max_length=7)),
                ('word8', models.CharField(max_length=7)),
                ('word9', models.CharField(max_length=7)),
                ('word10', models.CharField(max_length=7)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companies')),
            ],
        ),
    ]
