# Generated by Django 4.2.1 on 2023-05-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_safety_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safety_words',
            old_name='user_id',
            new_name='user',
        ),
    ]
