# Generated by Django 4.2.1 on 2023-06-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_id_safety_words_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='opinions',
            options={'verbose_name_plural': 'Opinions'},
        ),
        migrations.RemoveField(
            model_name='companies',
            name='login',
        ),
        migrations.AddField(
            model_name='companies',
            name='username',
            field=models.CharField(default='test', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinions',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='comment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='company_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
